
module.exports = {
    PERSON_DATA: 'PERSON_DATA',
    USER_POINTS: 'USER_POINTS',
    QUESTIONS_DATA: 'QUESTIONS_DATA'
    // RECEIVE_MOVIES: 'RECEIVE_MOVIES',
    // ERROR_FETCHING_MOVIES: 'ERROR_FETCHING_MOVIES',
    // FETCH_MOVIES: 'FETCH_MOVIES'
};